#!/bin/bash
echo "Execute it in the build directory !"
echo "Remeber to provide a seed with the -s argument"

sleep 1


mkdir -p dd_logs

echo "Build initial sequence"
./test1 "$@" -i | grep "InitDD" > dd_logs/init

echo "Run HH"
./test1 "$@" -d | grep "ResDD" > dd_logs/res

echo "Run HH RLE"
./test1 "$@" -d -r | grep "ResDD" > dd_logs/res_rle

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
gnuplot $DIR/compare_degree_dists.gp